sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t yacobdkr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yacobdkr/docker-react npm run test